name: Publish

on:
  push:

env:
  COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"

jobs:
  publish:
    if: github.repository == 'Adrigamer2950/Zenith'
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
        name: Checkout sources

      - uses: actions/setup-java@v5
        name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v5
        name: Setup Gradle

      - name: Publish Artifact
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
        run: "./gradlew publish -PNEXUS_USERNAME=$NEXUS_USERNAME -PNEXUS_PASSWORD=$NEXUS_PASSWORD"